/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAgencyRouteImport } from './routes/_authenticated/agency'
import { Route as AuthenticatedCanvasRouteImport } from './routes/_authenticated/canvas'
import { Route as AuthenticatedAgencyMeRouteImport } from './routes/_authenticated/agency.me'
import { Route as AuthenticatedBillingSuccessRouteImport } from './routes/_authenticated/billing.success'
import { Route as AuthenticatedNodeIdRouteImport } from './routes/_authenticated/node.$id'
import { Route as AuthenticatedAgencyMembersUserIdRouteImport } from './routes/_authenticated/agency.members.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgencyRoute = AuthenticatedAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCanvasRoute = AuthenticatedCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgencyMeRoute = AuthenticatedAgencyMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedAgencyRoute,
} as any)
const AuthenticatedBillingSuccessRoute =
  AuthenticatedBillingSuccessRouteImport.update({
    id: '/billing/success',
    path: '/billing/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodeIdRoute = AuthenticatedNodeIdRouteImport.update({
  id: '/node/$id',
  path: '/node/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgencyMembersUserIdRoute =
  AuthenticatedAgencyMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => AuthenticatedAgencyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agency': typeof AuthenticatedAgencyRouteWithChildren
  '/canvas': typeof AuthenticatedCanvasRoute
  '/agency/me': typeof AuthenticatedAgencyMeRoute
  '/billing/success': typeof AuthenticatedBillingSuccessRoute
  '/node/$id': typeof AuthenticatedNodeIdRoute
  '/agency/members/$userId': typeof AuthenticatedAgencyMembersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/agency': typeof AuthenticatedAgencyRouteWithChildren
  '/canvas': typeof AuthenticatedCanvasRoute
  '/agency/me': typeof AuthenticatedAgencyMeRoute
  '/billing/success': typeof AuthenticatedBillingSuccessRoute
  '/node/$id': typeof AuthenticatedNodeIdRoute
  '/agency/members/$userId': typeof AuthenticatedAgencyMembersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/agency': typeof AuthenticatedAgencyRouteWithChildren
  '/_authenticated/canvas': typeof AuthenticatedCanvasRoute
  '/_authenticated/agency/me': typeof AuthenticatedAgencyMeRoute
  '/_authenticated/billing/success': typeof AuthenticatedBillingSuccessRoute
  '/_authenticated/node/$id': typeof AuthenticatedNodeIdRoute
  '/_authenticated/agency/members/$userId': typeof AuthenticatedAgencyMembersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/agency'
    | '/canvas'
    | '/agency/me'
    | '/billing/success'
    | '/node/$id'
    | '/agency/members/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/agency'
    | '/canvas'
    | '/agency/me'
    | '/billing/success'
    | '/node/$id'
    | '/agency/members/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/agency'
    | '/_authenticated/canvas'
    | '/_authenticated/agency/me'
    | '/_authenticated/billing/success'
    | '/_authenticated/node/$id'
    | '/_authenticated/agency/members/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agency': {
      id: '/_authenticated/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AuthenticatedAgencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canvas': {
      id: '/_authenticated/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof AuthenticatedCanvasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agency/me': {
      id: '/_authenticated/agency/me'
      path: '/me'
      fullPath: '/agency/me'
      preLoaderRoute: typeof AuthenticatedAgencyMeRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
    '/_authenticated/billing/success': {
      id: '/_authenticated/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof AuthenticatedBillingSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/node/$id': {
      id: '/_authenticated/node/$id'
      path: '/node/$id'
      fullPath: '/node/$id'
      preLoaderRoute: typeof AuthenticatedNodeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agency/members/$userId': {
      id: '/_authenticated/agency/members/$userId'
      path: '/members/$userId'
      fullPath: '/agency/members/$userId'
      preLoaderRoute: typeof AuthenticatedAgencyMembersUserIdRouteImport
      parentRoute: typeof AuthenticatedAgencyRoute
    }
  }
}

interface AuthenticatedAgencyRouteChildren {
  AuthenticatedAgencyMeRoute: typeof AuthenticatedAgencyMeRoute
  AuthenticatedAgencyMembersUserIdRoute: typeof AuthenticatedAgencyMembersUserIdRoute
}

const AuthenticatedAgencyRouteChildren: AuthenticatedAgencyRouteChildren = {
  AuthenticatedAgencyMeRoute: AuthenticatedAgencyMeRoute,
  AuthenticatedAgencyMembersUserIdRoute: AuthenticatedAgencyMembersUserIdRoute,
}

const AuthenticatedAgencyRouteWithChildren =
  AuthenticatedAgencyRoute._addFileChildren(AuthenticatedAgencyRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgencyRoute: typeof AuthenticatedAgencyRouteWithChildren
  AuthenticatedCanvasRoute: typeof AuthenticatedCanvasRoute
  AuthenticatedBillingSuccessRoute: typeof AuthenticatedBillingSuccessRoute
  AuthenticatedNodeIdRoute: typeof AuthenticatedNodeIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgencyRoute: AuthenticatedAgencyRouteWithChildren,
  AuthenticatedCanvasRoute: AuthenticatedCanvasRoute,
  AuthenticatedBillingSuccessRoute: AuthenticatedBillingSuccessRoute,
  AuthenticatedNodeIdRoute: AuthenticatedNodeIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
