/** Website-capable @assistant-ui registry items installed for the Orch composer. */

export const ASSISTANT_UI_EXCLUDED_ITEMS = [
  "elements-computer-use",
  "eve-chat",
  "ai-sdk-backend",
  "ai-sdk-backend-resumable",
  "chat/b/ai-sdk-quick-start/json",
] as const;

export const ASSISTANT_UI_UNMOUNTED_LAUNCHERS = [
  "assistant-modal",
  "launcher-bubble",
  "elements-launcher-bubble",
] as const;

export const ASSISTANT_UI_WEBSITE_ITEMS = [
  "elements-surfaces",
  "elements-range",
  "elements-loading-state",
  "elements-thinking-indicator",
  "elements-reasoning-panel",
  "elements-streaming-text",
  "elements-typing-indicator",
  "elements-message-pair",
  "elements-message-branches",
  "elements-message-actions",
  "elements-suggestions",
  "elements-error-state",
  "elements-tool-call",
  "elements-tool-timeline",
  "elements-terminal-block",
  "elements-code-diff",
  "elements-web-search",
  "elements-sources",
  "elements-inline-citation",
  "elements-image-generation",
  "elements-data-table",
  "elements-number-ticker",
  "elements-agent-plan",
  "elements-subagent-list",
  "elements-agent-status",
  "elements-approval-card",
  "elements-recommendation-card",
  "elements-artifact-card",
  "elements-composer",
  "elements-chat-panel",
  "elements-empty-state",
  "elements-thread-list",
  "elements-scroll-anchor",
  "elements-todo-list",
  "elements-message-queue",
  "elements-message-attachment",
  "elements-reviewable-diff",
  "elements-file-tree",
  "elements-elicitation-form",
  "elements-retrieval-chunks",
  "elements-chart",
  "elements-trace-waterfall",
  "elements-canvas-split",
  "elements-voice-conversation",
  "elements-read-aloud",
  "elements-mcp-server-panel",
  "elements-feedback-dialog",
  "elements-quote-reply",
  "elements-edit-message",
  "elements-stopped-run",
  "elements-message-timing",
  "elements-connection-state",
  "elements-agent-card",
  "elements-web-preview",
  "elements-draft-restore",
  "elements-diagram",
  "elements-flow-graph",
  "elements-activity-graph",
  "elements-tool-group",
  "elements-context-breakdown",
  "elements-model-picker",
  "elements-reasoning-effort",
  "elements-guardrail-notice",
  "elements-day-separator",
  "elements-speaker-identity",
  "elements-regenerate-menu",
  "elements-confidence-marker",
  "elements-tool-error",
  "elements-permission-grant",
  "elements-code-runner",
  "elements-document-reference",
  "elements-memory-chips",
  "elements-research-report",
  "elements-map-answer",
  "elements-math-block",
  "elements-spec-sheet",
  "elements-comparison-card",
  "elements-timeline",
  "elements-job-progress",
  "elements-score-breakdown",
  "elements-cost-meter",
  "elements-quota-banner",
  "elements-agent-handoff",
  "elements-background-inbox",
  "elements-checkpoint-history",
  "elements-schedule-card",
  "elements-prompt-library",
  "elements-command-palette",
  "elements-shared-conversation",
  "elements-conversation-search",
  "elements-thread-search",
  "elements-launcher-bubble",
  "elements-settings-panel",
  "elements-onboarding",
  "elements-mobile-composer",
  "shimmer-style",
  "thread",
  "voice",
  "markdown-text",
  "reasoning",
  "message-timing",
  "context-display",
  "thread-list",
  "mcp-config",
  "attachment",
  "follow-up-suggestions",
  "tooltip-icon-button",
  "syntax-highlighter",
  "assistant-modal",
  "assistant-sidebar",
  "tool-fallback",
  "tool-group",
  "shiki-highlighter",
  "mermaid-diagram",
  "diff-viewer",
  "threadlist-sidebar",
  "quote",
  "sources",
  "image",
  "file",
  "model-selector",
  "logos",
  "select",
  "direction",
  "badge",
  "tabs",
  "accordion",
  "dot-matrix",
  "number-roll",
  "heat-graph",
  "composer-trigger-popover",
  "directive-text",
  "generative-ui-style",
  "generative-ui",
] as const;

export type AssistantUiWebsiteItem = (typeof ASSISTANT_UI_WEBSITE_ITEMS)[number];
export type AssistantUiExcludedItem = (typeof ASSISTANT_UI_EXCLUDED_ITEMS)[number];
export type AssistantUiUnmountedLauncher = (typeof ASSISTANT_UI_UNMOUNTED_LAUNCHERS)[number];

export function isAssistantUiExcluded(item: string): boolean {
  return (ASSISTANT_UI_EXCLUDED_ITEMS as readonly string[]).includes(item);
}

export function isAssistantUiLauncherMounted(item: string): boolean {
  if (item === "elements-launcher-bubble") return false;
  return !(ASSISTANT_UI_UNMOUNTED_LAUNCHERS as readonly string[]).includes(item);
}

export function listMountedAssistantUiItems(): string[] {
  return ASSISTANT_UI_WEBSITE_ITEMS.filter(
    (item) => !isAssistantUiExcluded(item) && isAssistantUiLauncherMounted(item),
  );
}
